Рефакторинг стейт менеджера
bem/yandex-ui-themer pull request #10
Opened 2021-04-23 18:37 UTC by Nnigmat

2021-04-23 19:57 UTC, stenin-nikita requested changes
В целом наверное ок. У меня есть пара замечаний, ну и так как я не знаю практически эффектор, то возможно Женя тут более компетентен будет

2021-04-23 19:57 UTC, stenin-nikita commented on src/components/Sandbox/CustomThemeDownloader/CustomThemeDownloader.tsx
> +        // hint={error}
Это забыл удалить или забыл вернуть?

2021-04-23 19:57 UTC, stenin-nikita commented on src/model/query.ts
> +export const $tokensQueryParameter = createStore<string>('')
Тут я не уверен, что хэш нужно также хранить в сторе, так как url сам по себе в каком-то смысле является стором. И получается, что если я вызову где-то `pushState`, то стор эффектора будет уже не актуален. По сути у тебя сейчас 2 источника данных, а это не очень хорошо.

2021-04-24 11:10 UTC, yarastqt commented on src/model/query.ts
> +export const $tokensQueryParameter = createStore<string>('')
Возможно нам не нужно вообще создавать стор для query-параметра 🤔

2021-04-24 11:10 UTC, yarastqt commented on src/model/query.ts
> +export const $tokensQueryParameter = createStore<string>('')
Если же нужно в модели подписаться на изменения query-параметров, то можно сделать так:

```js
function init() {
  window.addEventListener('popstate', (event) => {
    // call effector events
  })
}

init()
```

2021-05-11 09:44 UTC, axaxaman commented on src/api/downloadTheme.ts
> +  const response = await fetch('https://themebox.now.sh', {
но пока можно оставить как есть

2021-05-11 10:08 UTC, yarastqt commented on src/components/Header/Share/model.ts
> +export const shareTokensLoading = shareTokensFx.pending
Это стор, а значит должен называться `$shareTokensLoading`

2021-05-11 10:08 UTC, yarastqt commented on src/components/Header/Share/model.ts
> +export const shareTokensEvent = createEvent<string>()
Написано, что в дженерике строка приходит, а выше я вижу `onClick={shareTokensEvent}`, значит ивент придет, где-то ошибка (возможно в компиляторе не включен strict-режим)

2021-05-11 10:08 UTC, yarastqt commented on src/components/Header/Share/model.ts
> +    } as ShareTokensFxPropsType),
По-моему в attach есть возможность прокинуть дженерик и можно без тайп-каста обойтись

2021-05-11 10:08 UTC, yarastqt commented on src/components/Header/Share/model.ts
> +    return await uploadTokens(themeName, tokens)
async + await не нужен, т.к. ты и так промис возвращаешь а в этой функции не ждешь выполнения для дальнейших действий

2021-05-11 10:08 UTC, yarastqt commented on src/components/Sandbox/CustomThemeDownloader/model.ts
> +export const uploadRawTokensLoading = uploadRawTokensFx.pending
`$uploadRawTokensLoading`

2021-05-11 10:08 UTC, yarastqt commented on src/components/Sandbox/CustomThemeDownloader/model.ts
> +  effect: createEffect(async ({ content, theme }: UploadRawTokensFxPropsType) => {
async-await не нужен

2021-05-11 11:00 UTC, Nnigmat commented on src/components/Header/Share/model.ts
> +export const shareTokensEvent = createEvent<string>()
В `tsconfig` strict режим включен. Если попытаться запустить функцию с числом, например, то он кидает ошибку. Убрал string тип

2021-05-11 12:43 UTC, Nnigmat commented
> ![Снимок экрана 2021-05-11 в 12 52 49](https://user-images.githubusercontent.com/7259199/117796500-d166b480-b257-11eb-9cb6-8f213d847c28.png)
> 
> так и должно быть?

Пофиксил. У тебя это происходило, когда нажимал сбросить и потом поделиться?

2021-05-11 13:34 UTC, Nnigmat commented on src/model/tokens.ts
> +import { createStore, createEvent, createEffect, forward, Store } from 'effector'
Попробую это дело потестить в отдельном ПРе

2021-05-12 10:56 UTC, merged